### ISSUE TITLE
Uncaught TypeError: repoUrl.replace is not a function

### ISSUE THREAD

**Issue by jerone** [atom/notifications#112]
These are the highlights of what I did when getting below error:
1. Create a new Atom package by using Package Generator.
2. Alter the code so I throws an error after window refresh.
3. Restart Atom / refresh window.

Has it something to do with the package requiring a repo url?

**Atom Version**: 1.6.0-beta7
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.62.1
### Stack Trace

Uncaught TypeError: repoUrl.replace is not a function

```
At C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\notification-issue.js:177

TypeError: repoUrl.replace is not a function
    at NotificationIssue.module.exports.NotificationIssue.getRepoUrl (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\notification-issue.js:177:40)
    at atom-notification.NotificationElement.renderFatalError (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\notification-element.js:167:28)
    at atom-notification.NotificationElement.render (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\notification-element.js:159:21)
    at atom-notification.NotificationElement.initialize (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\notification-element.js:50:33)
    at Object.createView (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\main.js:96:42)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\view-registry.js:113:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\view-registry.js:86:21)
    at Object.Notifications.addNotificationView (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\main.js:130:60)
    at C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\notifications\lib\main.js:34:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addFatalError (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\notification-manager.js:45:19)
    at Package.module.exports.Package.handleError (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\package.js:1040:39)
    at Package.module.exports.Package.activateNow (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\package.js:188:14)
    at C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.__bind [as handleCommandEvent] (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\jerone\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:34.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-jade",
      "json-schema",
      "tool-bar-main",
      "minimap-highlight-selected"
    ],
    "packagesWithKeymapsDisabled": [
      "conventional-changelog"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "notifications": {
    "showErrorsInDevMode": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-json-editor, v0.4.1
atom-less, v0.1.10
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.0
atom-minify, v0.7.1
bottom-dock, v0.3.7
coffee-refactor, v0.7.0
color-picker, v2.1.1
custom-folds, v1.5.2
editorconfig, v1.2.4
file-icons, v1.6.17
flex-tool-bar, v0.7.3
foldername-tabs, v0.1.11
gutter-shadow, v0.6.0
imdone-atom, v1.3.27
indentation-indicator, v0.6.0
jade-autocompile, v0.8.3
language-actionscript3, v0.3.0
language-jade, v0.6.3
less-postcss-autocompile, v1.2.3
less-than-slash, v0.12.3
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jade, v0.3.2
linter-jshint, v2.0.2
linter-just-say-no, v0.6.1
linter-less, v2.4.2
linter-manager, v0.2.9
linter-markdown, v1.5.0
linter-sass-lint, v1.1.1
linter-scspell, v2.0.1
markdown-scroll-sync, v2.1.2
menu-manager, v0.4.4
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
new-tab, v0.5.1
open-recent, v5.0.0
pigments, v0.24.2
pinned-tabs, v0.1.13
project-view, v0.5.0
refactor, v0.6.0
sass-autocompile, v0.12.3
soft-wrap-indicator, v0.7.0
sync-settings, v0.6.0
tool-bar, v0.3.0

# Dev
flex-tool-bar, v0.7.3
tool-bar, v0.3.0
```

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
