### ISSUE TITLE
Create issue on atom/atom -> 414 Request-URI Too Large

### ISSUE THREAD

**Issue by AgentME** [atom/notifications#129]
I ran into an Atom bug, and a red notification popped up prompting me to create an issue. When I clicked it, it lead me to [this URL](https://github.com/atom/atom/issues/new?title=Uncaught%20Error:%20Cannot%20read%20property%20%27object%27%20of%20undefined%0ATypeError:%20Cannot%20read%20property%20%27objec...&body=[Enter%20steps%20to%20reproduce%20below:]%0A%0A1.%20...%0A2.%20...%0A%0A**Atom%20Version**:%201.9.8%0A**System**:%20Mac%20OS%20X%2010.11.4%0A**Thrown%20From**:%20Atom%20Core%0A%0A%0A%23%23%23%20Stack%20Trace%0A%0AUncaught%20Error:%20Cannot%20read%20property%20%27object%27%20of%20undefined%0ATypeError:%20Cannot%20read%20property%20%27object%27%20of%20undefined%0A%20%20%20%20at%20ObjectsRegistry.get%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)%0A%20%20%20%20at%20EventEmitter.%3Canonymous%3E%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)%0A%20%20%20%20at%20emitMany%20(events.js:121:13)%0A%20%20%20%20at%20EventEmitter.emit%20(events.js:195:7)%0A%20%20%20%20at%20EventEmitter.%3Canonymous%3E%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)%0A%20%20%20%20at%20emitTwo%20(events.js:100:13)%0A%20%20%20%20at%20EventEmitter.emit%20(events.js:185:7)%0A%0A```%0AAt%20/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178%0A%0AError:%20Cannot%20read%20property%20%27object%27%20of%20undefined%0ATypeError:%20Cannot%20read%20property%20%27object%27%20of%20undefined%0A%20%20%20%20at%20ObjectsRegistry.get%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)%0A%20%20%20%20at%20EventEmitter.%3Canonymous%3E%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)%0A%20%20%20%20at%20emitMany%20(events.js:121:13)%0A%20%20%20%20at%20EventEmitter.emit%20(events.js:195:7)%0A%20%20%20%20at%20EventEmitter.%3Canonymous%3E%20(/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)%0A%20%20%20%20at%20emitTwo%20(events.js:100:13)%0A%20%20%20%20at%20EventEmitter.emit%20(events.js:185:7)%0A%20%20%20%20at%20metaToValue%20(/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)%0A%20%20%20%20at%20undefined.remoteMemberFunction%20(/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)%0A%20%20%20%20at%20AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions%20(/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:631:29)%0A%20%20%20%20at%20AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions%20(/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:665:36)%0A%20%20%20%20at%20WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur%20(/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:182:35)%0A%20%20%20%20at%20/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61%0A```%0A%0A%23%23%23%20Commands%0A%0A```%0A%20%20%20%20%20-0:20.5.0%20core:copy%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:19.6.0%20editor:newline%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:19.4.0%20core:paste%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:19%20core:backspace%20(atom-text-editor.editor.is-focused)%0A%2010x%20-0:18.5.0%20editor:move-to-beginning-of-word%20(atom-text-editor.editor.is-focused)%0A%20%206x%20-0:16.3.0%20core:move-left%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:15.1.0%20core:move-right%20(atom-text-editor.editor.is-focused)%0A%20%207x%20-0:14.9.0%20core:backspace%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:12.3.0%20autocomplete-plus:confirm%20(atom-text-editor.editor.is-focused.autocomplete-active)%0A%20%206x%20-0:11.3.0%20editor:move-to-end-of-word%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:09.0%20editor:select-to-end-of-word%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:05.8.0%20core:backspace%20(atom-text-editor.editor.is-focused.autocomplete-active)%0A%20%203x%20-0:02.7.0%20core:move-right%20(atom-text-editor.editor.is-focused.autocomplete-active)%0A%20%20%20%20%20-0:01.7.0%20editor:move-to-end-of-screen-line%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:01.4.0%20core:move-right%20(atom-text-editor.editor.is-focused)%0A%20%20%20%20%20-0:01.0%20core:save%20(atom-text-editor.editor.is-focused)%0A```%0A%0A%23%23%23%20Config%0A%0A```json%0A{%0A%20%20%22core%22:%20{%0A%20%20%20%20%22disabledPackages%22:%20[%0A%20%20%20%20%20%20%22ide-flow%22,%0A%20%20%20%20%20%20%22node-resolver%22,%0A%20%20%20%20%20%20%22linter-jshint%22%0A%20%20%20%20]%0A%20%20},%0A%20%20%22editor%22:%20{%0A%20%20%20%20%22fontSize%22:%2013,%0A%20%20%20%20%22invisibles%22:%20{},%0A%20%20%20%20%22softWrap%22:%20true%0A%20%20}%0A}%0A```%0A%0A%23%23%23%20Installed%20Packages%0A%0A```coffee%0A%23%20User%0Aatom-beautify,%20v0.29.10%20(active)%0Aatom-html-preview,%20v0.1.22%20(active)%0Aauto-detect-indentation,%20v1.1.0%20(active)%0Acolor-picker,%20v2.2.2%20(active)%0Aescape-utils,%20v0.5.3%20(inactive)%0Ahtml-entities,%20v0.4.0%20(active)%0Aide-flow,%20v0.8.0%20(inactive)%0Alanguage-diff,%20v0.4.0%20(active)%0Alanguage-haskell,%20v1.9.3%20(active)%0Alanguage-lisp,%20v0.2.0%20(active)%0Alinter,%20v1.11.16%20(active)%0Alinter-eslint,%20v7.2.4%20(active)%0Alinter-flow,%20v5.5.0%20(active)%0Alinter-jshint,%20v2.1.0%20(inactive)%0Aminimap,%20v4.24.7%20(active)%0Anode-resolver,%20v1.0.1%20(inactive)%0AParinfer,%20v1.15.0%20(active)%0Areact,%20v0.16.0%20(active)%0Asort-lines,%20v0.14.0%20(inactive)%0Aatom-dark-syntax,%20v0.27.0%20(inactive)%0Aatom-dark-ui,%20v0.51.0%20(inactive)%0Aatom-light-syntax,%20v0.28.0%20(inactive)%0Aatom-light-ui,%20v0.43.0%20(inactive)%0Abase16-tomorrow-dark-theme,%20v1.1.0%20(inactive)%0Abase16-tomorrow-light-theme,%20v1.1.1%20(inactive)%0Aone-dark-ui,%20v1.3.2%20(active)%0Aone-light-ui,%20v1.3.2%20(inactive)%0Aone-dark-syntax,%20v1.2.0%20(active)%0Aone-light-syntax,%20v1.2.0%20(inactive)%0Asolarized-dark-syntax,%20v1.0.2%20(inactive)%0Asolarized-light-syntax,%20v1.0.2%20(inactive)%0Aabout,%20v1.5.2%20(active)%0Aarchive-view,%20v0.61.1%20(active)%0Aautocomplete-atom-api,%20v0.10.0%20(active)%0Aautocomplete-css,%20v0.11.1%20(active)%0Aautocomplete-html,%20v0.7.2%20(active)%0Aautocomplete-plus,%20v2.31.0%20(active)%0Aautocomplete-snippets,%20v1.11.0%20(active)%0Aautoflow,%20v0.27.0%20(inactive)%0Aautosave,%20v0.23.1%20(active)%0Abackground-tips,%20v0.26.0%20(active)%0Abookmarks,%20v0.41.0%20(active)%0Abracket-matcher,%20v0.82.1%20(active)%0Acommand-palette,%20v0.38.0%20(inactive)%0Adeprecation-cop,%20v0.54.1%20(active)%0Adev-live-reload,%20v0.47.0%20(active)%0Aencoding-selector,%20v0.22.0%20(active)%0Aexception-reporting,%20v0.39.0%20(active)%0Afuzzy-finder,%20v1.3.0%20(active)%0Agit-diff,%20v1.1.0%20(active)%0Afind-and-replace,%20v0.198.0%20(active)%0Ago-to-line,%20v0.31.0%20(inactive)%0Agrammar-selector,%20v0.48.1%20(active)%0Aimage-view,%20v0.58.0%20(active)%0Aincompatible-packages,%20v0.26.1%20(active)%0Akeybinding-resolver,%20v0.35.0%20(active)%0Aline-ending-selector,%20v0.5.0%20(active)%0Alink,%20v0.31.1%20(inactive)%0Amarkdown-preview,%20v0.158.0%20(active)%0Ametrics,%20v0.53.1%20(active)%0Anotifications,%20v0.64.1%20(active)%0Aopen-on-github,%20v1.2.0%20(inactive)%0Apackage-generator,%20v1.0.0%20(inactive)%0Asettings-view,%20v0.238.2%20(active)%0Asnippets,%20v1.0.2%20(active)%0Aspell-check,%20v0.67.1%20(active)%0Astatus-bar,%20v1.4.1%20(active)%0Astyleguide,%20v0.46.0%20(active)%0Asymbols-view,%20v0.113.0%20(inactive)%0Atabs,%20v0.98.1%20(active)%0Atimecop,%20v0.33.1%20(active)%0Atree-view,%20v0.208.0%20(active)%0Aupdate-package-dependencies,%20v0.10.0%20(active)%0Awelcome,%20v0.34.0%20(active)%0Awhitespace,%20v0.32.2%20(active)%0Awrap-guide,%20v0.38.1%20(active)%0Alanguage-c,%20v0.52.1%20(active)%0Alanguage-clojure,%20v0.21.0%20(active)%0Alanguage-coffee-script,%20v0.47.0%20(active)%0Alanguage-csharp,%20v0.12.1%20(active)%0Alanguage-css,%20v0.36.2%20(active)%0Alanguage-gfm,%20v0.86.0%20(active)%0Alanguage-git,%20v0.13.0%20(active)%0Alanguage-go,%20v0.42.0%20(active)%0Alanguage-html,%20v0.44.1%20(active)%0Alanguage-hyperlink,%20v0.16.0%20(active)%0Alanguage-java,%20v0.22.0%20(active)%0Alanguage-javascript,%20v0.119.0%20(active)%0Alanguage-json,%20v0.18.0%20(active)%0Alanguage-less,%20v0.29.3%20(active)%0Alanguage-make,%20v0.22.2%20(active)%0Alanguage-mustache,%20v0.13.0%20(active)%0Alanguage-objective-c,%20v0.15.1%20(active)%0Alanguage-perl,%20v0.35.0%20(active)%0Alanguage-php,%20v0.37.0%20(active)%0Alanguage-property-list,%20v0.8.0%20(active)%0Alanguage-python,%20v0.45.0%20(active)%0Alanguage-ruby,%20v0.68.5%20(active)%0Alanguage-ruby-on-rails,%20v0.25.0%20(active)%0Alanguage-sass,%20v0.52.0%20(active)%0Alanguage-shellscript,%20v0.22.3%20(active)%0Alanguage-source,%20v0.9.0%20(active)%0Alanguage-sql,%20v0.21.1%20(active)%0Alanguage-text,%20v0.7.1%20(active)%0Alanguage-todo,%20v0.28.0%20(active)%0Alanguage-toml,%20v0.18.0%20(active)%0Alanguage-xml,%20v0.34.8%20(active)%0Alanguage-yaml,%20v0.26.0%20(active)%0A%0A%23%20Dev%0ANo%20dev%20packages%0A```%0A%0A), which causes Github to give me an error page: "414 Request-URI Too Large -- nginx".

I assume this is a duplicate of https://github.com/atom/notifications/issues/89, but that was marked fixed last year.

**Comment by poci-hu** [comment]
Same here, but nothing happend on click for me, didn't open github

**Comment by adamboche** [comment]
Same. For context, this is the error I was trying to report, from a package.



**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /home/adam/.atom/packages/python-indent/lib/python-indent.js:8

TypeError: Cannot read property 'getGrammar' of undefined
    at PythonIndent.properlyIndent (/home/adam/.atom/packages/python-indent/lib/python-indent.js:8:24)
    at atom-text-editor.editorNewline (/home/adam/.atom/packages/python-indent/lib/main.js:22:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:44.8.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
  4x -0:40.9.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:40.2.0 atomic-emacs:next-line (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:39.8.0 editor:move-to-end-of-word (atom-text-editor.editor.emacs-plus.is-focused)
     -0:39.1.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:38.9.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:34.2.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:34 atomic-emacs:next-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:33.5.0 atomic-emacs:previous-line (atom-text-editor.editor.emacs-plus.is-focused)
 10x -0:32.6.0 core:move-right (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:31.7.0 core:move-left (atom-text-editor.editor.emacs-plus.is-focused)
     -0:31.2.0 emacs-plus:kill-word (atom-text-editor.editor.emacs-plus.is-focused)
     -0:30.8.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:00.6.0 core:move-right (atom-text-editor.editor.emacs-plus.is-focused)
     -0:00.4.0 settings-view:open (atom-text-editor.editor.emacs-plus.is-focused)
     -0:00.1.0 editor:newline (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [
      "linter-pylama",
      "atom-dpaste"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (active)
atom-dpaste, v0.1.5 (active)
atom-material-numix-syntax, v0.2.1 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.6 (active)
atom-monokai, v0.10.4 (inactive)
atom-pastebin, v0.2.0 (active)
atom-python-test, v0.3.1 (active)
atomic-emacs, v0.9.2 (active)
autocomplete-python, v1.8.6 (active)
clipboard-plus, v0.5.1 (active)
disable-keybindings, v0.6.0 (active)
emacs-plus, v0.11.0 (active)
fonts, v1.6.0 (active)
git-plus, v5.16.2 (inactive)
linter, v1.11.16 (active)
linter-pylama, v0.7.1 (active)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
monokai-flat, v1.0.1 (inactive)
monokai-slate, v0.5.0 (inactive)
nucleus-dark-ui, v0.9.3 (inactive)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
script, v3.9.0 (inactive)
sync-settings, v0.7.2 (active)
tabs-to-spaces, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ProLoser** [comment]
I have this problem too, I believe it's due to the number of packages being listed (NOT the stack trace). Why not simply ensure the URI doesn't exceed the HTTP spec and pass an ellipses if it does (better than having to cut and paste everything). Alternatively, I'd propose truncating the list of packages (which truncating the entire URI essentially does)

**Comment by vjandrea** [comment]
I suggest an option to dump the issue in a file, as a plain text or markdown.

**Comment by RafaelLinux** [comment]
Still same problem. I have installed "theme-alien-syntax" resulting in an deprecation notification, that brings me to "Deprecation Cop" window, where, if I click on "Report issue" button at the bottom of the page, my web browse is opened and shows "414 Request-URI Too Large".

:(
