### ISSUE TITLE
Uncaught TypeError: src.replace is not a function

### ISSUE THREAD

**Issue by anaibol** [atom/notifications#133]
**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: "Arch Linux"
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.65.1

### Stack Trace

Uncaught TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.

```
At /usr/share/atom/resources/app.asar/node_modules/marked/lib/marked.js:1227

TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/usr/share/atom/resources/app.asar/node_modules/marked/lib/marked.js:138:6)
    at Function.Lexer.lex (/usr/share/atom/resources/app.asar/node_modules/marked/lib/marked.js:129:16)
    at marked (/usr/share/atom/resources/app.asar/node_modules/marked/lib/marked.js:1219:31)
    at atom-notification.NotificationElement.render (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:113:33)
    at atom-notification.NotificationElement.initialize (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:50:33)
    at Object.createView (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/main.js:89:42)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:119:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at Object.Notifications.addNotificationView (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/main.js:123:60)
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/main.js:27:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (/usr/share/atom/resources/app.asar/src/notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addError (/usr/share/atom/resources/app.asar/src/notification-manager.js:41:19)
    at Object.module.exports.Config.getJson (/home/anaibol/.atom/packages/Hydrogen/lib/config.coffee:10:32)
    at KernelManager.module.exports.KernelManager.kernelSpecProvidesLanguage (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:188:33)
    at /home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:163:22
    at Array.filter (native)
    at /home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:162:37
    at KernelManager.module.exports.KernelManager.getAllKernelSpecs (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:156:13)
    at KernelManager.getAllKernelSpecs (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:1:1)
    at KernelManager.module.exports.KernelManager.getAllKernelSpecsFor (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:161:14)
    at KernelManager.module.exports.KernelManager.getKernelSpecFor (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:174:10)
    at KernelManager.module.exports.KernelManager.startKernelFor (/home/anaibol/.atom/packages/Hydrogen/lib/kernel-manager.coffee:75:10)
    at Object.module.exports.Hydrogen.createResultBubble (/home/anaibol/.atom/packages/Hydrogen/lib/main.coffee:236:24)
    at Object.module.exports.Hydrogen.run (/home/anaibol/.atom/packages/Hydrogen/lib/main.coffee:322:14)
    at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (/home/anaibol/.atom/packages/Hydrogen/lib/main.coffee:54:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:11.3.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "hidpi",
      "vim-mode",
      "atom-html-preview",
      "Stylus",
      "atom-bootstrap3",
      "atom-fuzzy-grep",
      "atom-handlebars",
      "atom-jade",
      "atom-terminal",
      "atom-terminal-panel",
      "css-snippets",
      "css-spy",
      "git-control",
      "git-plus",
      "terminal-status",
      "fancy-bracket-matcher",
      "json-schema",
      "json-path-finder",
      "linter-stylint",
      "icon-fonts",
      "keyboard-localization",
      "last-tab",
      "linter-bootlint",
      "sync-settings",
      "atom-ternjs",
      "import",
      "gist-it",
      "merge-conflicts",
      "open-recent",
      "quantum-shell",
      "term",
      "terminal-plus",
      "auto-indent",
      "auto-detect-indentation",
      "react-es6-snippets",
      "jump-to-import",
      "js-autoimport",
      "autocomplete-paths",
      "file-icons",
      "incremental-search",
      "color-picker",
      "react",
      "linter-flow-plus",
      "autohide-tree-view",
      "es6-javascript",
      "language-javascript-jsx",
      "javascript-snippets"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
apathy-theme, v1.10.6 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-fuzzy-grep, v0.15.0 (inactive)
atom-handlebars, v1.3.0 (inactive)
atom-html-preview, vundefined (inactive)
atom-jade, v0.3.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-no-tab-close-button, v1.0.0 (active)
atom-terminal, v0.8.0 (inactive)
atom-terminal-panel, v4.4.4 (inactive)
atom-ternjs, v0.15.0 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
auto-indent, v0.5.0 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-flow, v1.6.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-paths, v1.0.2 (inactive)
autohide-tree-view, v0.25.1 (inactive)
color-picker, v2.2.2 (inactive)
css-snippets, v1.1.0 (inactive)
css-spy, v0.6.0 (inactive)
dark-flat-ui, v1.2.4 (inactive)
dockerletion, v0.2.0 (active)
editor-stats, v0.17.0 (active)
editorconfig, v1.7.2 (active)
enhanced-tabs, v1.7.0 (inactive)
es6-javascript, v1.0.0 (inactive)
fancy-bracket-matcher, v0.4.1 (inactive)
file-icons, v1.7.23 (inactive)
flow-ide, v1.1.9 (active)
foldername-tabs, v0.2.4 (active)
gist-it, v0.9.1 (inactive)
git-control, v0.8.2 (inactive)
git-plus, v5.18.0 (inactive)
git-time-machine, v1.5.3 (inactive)
hidpi, v0.12.0 (inactive)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.15.0 (active)
hyperclick, v0.0.39 (active)
icon-fonts, v2.8.8 (inactive)
import, v1.7.0 (inactive)
incremental-search, v5.1.0 (inactive)
javascript-snippets, v1.2.1 (inactive)
js-autoimport, v0.5.1 (inactive)
js-hyperclick, v1.9.0 (active)
json-path-finder, v0.1.8 (inactive)
json-schema, v0.1.15 (inactive)
jump-to-import, v1.4.0 (inactive)
keyboard-localization, v1.4.18 (inactive)
language-babel, v2.45.0 (active)
language-docker, v1.1.7 (active)
language-fish-shell, v1.0.5 (active)
language-graphql, v0.7.0 (active)
language-ignore, v1.5.1 (active)
language-javascript-jsx, v0.3.7 (inactive)
last-cursor-position, v0.9.0 (active)
last-tab, v0.1.6 (inactive)
lazy-motion, v0.4.0 (inactive)
less-than-slash, v0.16.0 (active)
linter, v1.11.18 (active)
linter-bootlint, v1.0.2 (inactive)
linter-csslint, v1.3.3 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v8.0.0 (active)
linter-flow, v5.5.0 (active)
linter-flow-plus, v3.1.0 (inactive)
linter-sass-lint, v1.7.1 (active)
linter-stylelint, v3.5.0 (active)
linter-stylint, v2.2.5 (inactive)
livestyle-atom, v0.2.7 (active)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.6 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
node-debugger, v1.9.1 (active)
nucleus-dark-ui, v0.10.12 (inactive)
open-recent, v5.0.0 (inactive)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
quantum-shell, v0.7.1 (inactive)
react, v0.16.1 (inactive)
react-es6-snippets, v0.3.0 (inactive)
remember-file-positions, v0.2.2 (active)
robin-hood-syntax, v1.0.0 (inactive)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
stylefmt, v3.2.1 (active)
Stylus, v3.1.0 (inactive)
sync-settings, v0.7.2 (inactive)
tab-control, v0.6.9 (active)
tab-title, v0.3.3 (active)
tag, v0.4.0 (active)
term, v0.2.4 (inactive)
terminal-plus, v0.14.5 (inactive)
terminal-status, v1.6.8 (inactive)
toggle-quotes, v1.0.0 (inactive)
vim-mode, v0.65.1 (inactive)
Visual-Studio-2015-Dark-Theme, v2.3.1 (inactive)
word-jumper, v0.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please report this to https://github.com/chjj/marked.
