### ISSUE TITLE
Uncaught TypeError: src.replace is not a functionPlease report this to https://github.com/chjj/m...

### ISSUE THREAD

**Issue by jhulten** [atom/notifications#151]
[Enter steps to reproduce:]

1. Activate imdone task board

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2

### Stack Trace

Uncaught TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/marked/lib/marked.js:1227

TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/app.asar/node_modules/marked/lib/marked.js:138:6)
    at Function.Lexer.lex (/app.asar/node_modules/marked/lib/marked.js:129:16)
    at marked (/app.asar/node_modules/marked/lib/marked.js:1219:31)
    at /app.asar/node_modules/notifications/lib/notification-element.js:115:33)
    at /app.asar/node_modules/notifications/lib/notification-element.js:52:33)
    at Object.createView (/app.asar/node_modules/notifications/lib/main.js:89:42)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:117:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at Object.addNotificationView (/app.asar/node_modules/notifications/lib/main.js:126:58)
    at /app.asar/node_modules/notifications/lib/main.js:27:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (/app.asar/src/notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addWarning (/app.asar/src/notification-manager.js:37:19)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:182:56
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at PluginViewInterface.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:126:25)
    at emitOne (events.js:96:13)
    at Repository.emit (events.js:188:7)
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:63:25
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:706:25
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:276:9
    at /packages/imdone-atom/node_modules/async/lib/async.js:52:16
    at /packages/imdone-atom/node_modules/async/lib/async.js:322:29
    at /packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:254:27
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:23
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:23.9.0 imdone-atom:tasks (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
ansible-vault 0.5.1 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.0 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-jinja2 0.6.0 
autocomplete-asciidoc 0.1.2 
autocomplete-elixir 1.5.14 
bottom-dock 0.4.4 
build 0.67.0 
build-cargo 2.0.0 
build-elixir 0.6.0 
build-make 0.13.0 
build-rake 0.1.1 
busy 0.7.0 
busy-signal 1.3.0 
ex-mode 0.14.0 
git-line 0.6.0 
git-plus 7.3.3 
Hydrogen 1.9.0 
iex 0.10.0 
imdone-atom 2.1.26 
imdone-atom-github 0.1.11 
intentions 1.1.2 
javascript-snippets 1.2.1 
jira-issue-search 1.0.3 
language-ansible 0.2.1 
language-asciidoc 1.10.0 
language-docker 1.1.7 
language-elixir 0.17.0 
language-rust 0.4.10 
language-todotxt 0.6.1 
language-viml 1.1.3 
linter 2.1.2 
linter-annotations 1.0.1 
linter-ansible-syntax 1.1.3 
linter-docker 0.1.5 
linter-erb 1.0.4 
linter-eslint 8.1.4 
linter-golinter 1.2.2 
linter-manager 0.2.12 
linter-rubocop 1.1.1 
linter-rust 0.8.0 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
merge-conflicts 1.4.4 
minimap 4.27.0 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-linter 2.0.0 
organized 0.6.6 
Parinfer 1.17.0 
pretty-json 1.6.3 
proto-repl 1.4.18 
proto-repl-charts 0.4.0 
react 0.16.2 
react-snippets 0.7.2 
rustfmt 0.1.3 
script 3.14.1 
todo-manager 0.2.10 
toggle-quotes 1.0.1 
vagrant 0.1.0 
vim-mode 0.66.0 
vim-modeline 0.5.2 
vim-surround 0.8.1 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by 50Wliu** [comment]
> Please report this to https://github.com/chjj/marked.
