### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by stephenmathieson** [atom/notifications#155]
Not totally sure what got me into this loop, but after closing all tabs in a pane, I'm repetitively being prompted with `Uncaught Error: Pane has been destroyed` and am unable to open any files.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:847

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:847:15)
    at /app.asar/node_modules/notifications/lib/notification-element.js:298:40)
    at /app.asar/node_modules/notifications/lib/notification-element.js:256:19)
    at /app.asar/node_modules/notifications/lib/notification-element.js:59:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Notification.module.exports.Notification.dismiss (/app.asar/src/notification.js:79:27)
    at /app.asar/node_modules/notifications/lib/notification-element.js:260:25)
    at /app.asar/node_modules/notifications/lib/notification-element.js:149:26)
```

### Commands

```
     -7:30.2.0 editor:newline (input.hidden-input)
     -7:29.7.0 editor:consolidate-selections (input.hidden-input)
     -7:29.7.0 core:cancel (input.hidden-input)
  2x -7:13.1.0 editor:newline (input.hidden-input)
 14x -7:09.6.0 core:backspace (input.hidden-input)
     -6:40.1.0 editor:move-to-end-of-line (input.hidden-input)
     -5:37.4.0 autocomplete-plus:cancel (input.hidden-input)
 12x -5:34.2.0 core:backspace (input.hidden-input)
     -5:08.3.0 editor:select-to-end-of-line (input.hidden-input)
     -5:08.1.0 core:backspace (input.hidden-input)
     -5:07.5.0 core:move-down (input.hidden-input)
     -4:48.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -4:48 core:backspace (input.hidden-input)
     -4:47.4.0 core:select-all (input.hidden-input)
     -4:47.1.0 core:cut (input.hidden-input)
  4x -0:49.5.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```
atom-gooey-syntax 0.2.1 
atom-jade 0.3.0 
atom-material-syntax 0.2.4 
atom-material-ui 0.8.0 
atom-spotify2 2.1.2 
busy-signal 1.3.0 
cssnano 1.1.0 
go-plus 5.3.3 
intentions 1.1.2 
language-babel 2.56.2 
language-docker 1.1.7 
language-dotenv 1.0.0 
language-hcl 0.4.0 
language-nginx 0.6.2 
language-patch 1.2.0 
linter 2.1.0 
linter-eslint 8.1.4 
linter-js-standard 3.9.0 
linter-ui-default 1.2.1 
pretty-json 1.6.1 
seti-syntax 0.4.1 
seti-ui 0.8.1 
sort-lines 0.14.0 
```

**Comment by rsese** [comment]
Are you able to start in safe mode (`atom --safe`)?

**Comment by rsese** [comment]
Going to go ahead and close for now but if you're still having this problem let me know and we can -reopen :v:
