### ISSUE TITLE
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration faile...

### ISSUE THREAD

**Issue by annamgithub** [atom/notifications#160]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.1
**Learn IDE Core**: 2.4.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.3
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.1

### Stack Trace

Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-notifications'. A type with that name is already registered.

```
At /Users/drew/Documents/development/atom/out/app/node_modules/notifications/lib/notifications-element.coffee:15

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-notifications'. A type with that name is already registered.
    at Error (native)
    at /app.asar/node_modules/notifications/lib/notifications-element.js:15:52)
    at /app.asar/node_modules/notifications/lib/notifications-element.js:19:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.initializeIfNotInitialized (/app.asar/node_modules/notifications/lib/main.js:86:30)
    at Object.addNotificationView (/app.asar/node_modules/notifications/lib/main.js:116:12)
    at /app.asar/node_modules/notifications/lib/main.js:27:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (/app.asar/src/notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addError (/app.asar/src/notification-manager.js:41:19)
    at Object.error (/packages/learn-ide-tree/lib/nsync/atom-helper.coffee:31:24)
    at /packages/learn-ide-tree/lib/nsync/initializer.coffee:163:20
    at Emitter.module.exports.Emitter.emit (/packages/learn-ide-tree/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.disconnectedSend (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:77:25)
    at Nsync.send (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:165:12)
    at Nsync.save (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:289:17)
    at /packages/learn-ide-tree/lib/nsync/initializer.coffee:62:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:55.3.0 core:undo (input.hidden-input)
     -2:40.9.0 core:paste (input.hidden-input)
     -2:12.3.0 find-and-replace:show (input.hidden-input)
  9x -2:09.6.0 core:confirm (input.hidden-input)
  4x -1:51.9.0 core:backspace (input.hidden-input)
 11x -1:49.9.0 core:confirm (input.hidden-input)
  7x -1:42.1.0 core:backspace (input.hidden-input)
  4x -1:39.9.0 core:confirm (input.hidden-input)
  5x -1:35.8.0 core:backspace (input.hidden-input)
     -1:34.1.0 core:confirm (input.hidden-input)
  4x -1:28.7.0 core:backspace (input.hidden-input)
  2x -1:26.7.0 core:move-down (input.hidden-input)
     -1:25.7.0 core:move-up (input.hidden-input)
 12x -1:25.3.0 core:move-left (input.hidden-input)
  3x -1:11.7.0 core:undo (input.hidden-input)
  3x -1:08.8.0 learn-ide:save (input.hidden-input)
```

### Non-Core Packages

```
learn-ide-notifications 0.66.5 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by [Learn IDE](https://atom.io/packages/learn-ide), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of Learn IDE to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by theomoji** [comment]
I am having the same problem after updating to IDE 3. I have wiped and reinstalled twice now. Learn IDE: attempting to reconnect...
CLOSE ALL
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-notifications'. A type with that name is already registered.
/Users/drew/Documents/development/atom/out/app/node_modules/notifications/lib/notifications-element.coffee:15
Show Stack Trace
The error was thrown from the learn-ide-3-notifications package.

**Comment by rsese** [comment]
@theomoji - similarly as mentioned [above](https://github.com/atom/notifications/issues/160#issuecomment-307464338), you should reach out to the the maintainers of the Learn IDE 3 packages.  The error you mentioned looks like it's already been reported: https://github.com/learn-co/learn-ide-3-notifications/issues/1
