### ISSUE TITLE
Failed to activate the notifications package

### ISSUE THREAD

**Issue by tbsharkey** [atom/notifications#165]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.4.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.1

### Stack Trace

Failed to activate the notifications package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-notifications'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-notifications'. A type with that name is already registered.
    at Error (native)
    at /app.asar/node_modules/notifications/lib/notifications-element.js:15:52)
    at /app.asar/node_modules/notifications/lib/notifications-element.js:19:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.initializeIfNotInitialized (/app.asar/node_modules/notifications/lib/main.js:86:30)
    at Object.addNotificationView (/app.asar/node_modules/notifications/lib/main.js:116:12)
    at Object.activate (/app.asar/node_modules/notifications/lib/main.js:23:14)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
     -7:41.3.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```
emmet 2.4.3 
learn-ide-notifications 0.66.5 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide-notifications](https://atom.io/packages/learn-ide-notifications) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
