### ISSUE TITLE
Uncaught TypeError: Cannot read property 'refs' of undefined

### ISSUE THREAD

**Issue by warwickrs** [atom/notifications#167]
[Enter steps to reproduce:]

1. Start Atom
2. Errors occur :(

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.67.2

### Stack Trace

Uncaught TypeError: Cannot read property 'refs' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1455

TypeError: Cannot read property 'refs' of undefined
    at TextEditorComponent.didFocus (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1455:58)
    at HTMLElement.addEventListener (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:36:67)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:54:18)
    at HTMLElement.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:913:33)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:294:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:252:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:54:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app/src/notification.js:79:33)
    at NotificationElement.module.exports.NotificationElement.handleRemoveAllNotificationsClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:265:30)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:152:32)
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
atom-material-ui 2.0.4 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.2.5 
hex 0.6.2 
intentions 1.1.5 
linter 2.2.0 
linter-jshint 3.1.5 
linter-perl 0.8.1 
linter-perl-check-syntax 0.8.1 
linter-php 1.3.2 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
native-ui 0.22.0 
pigments 0.40.2 
project-manager 3.3.5 
project-sidebar 1.3.0 
regex-railroad-diagram 0.19.3 
svn 0.0.13 
tab-title 0.3.4 
```

**Comment by warwickrs** [comment]
I have disabled tab-title and the problem disappears, so I'd assume the bug is in that package.

**Comment by Ben3eeE** [comment]
@as-cii @nathansobo `tab-title` is completely broken on Atom 1.19 and this is the second report we have for `'refs' of undefined` in `didFocus` /cc: https://github.com/atom/atom/issues/15227
