### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by bfontana** [atom/notifications#174]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.69.0

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:916

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:916:21)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:294:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:252:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:54:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app/src/notification.js:79:33)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:256:31)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:145:32)
```

### Commands

```
```

### Non-Core Packages

```
browser-plus 0.0.98 
centurion-ui 0.5.0 
docker 0.8.0 
language-plantuml 0.2.0 
markdown-preview-plus 2.4.10 
plantuml 0.1.2 
plantuml-preview 0.12.9 
plantuml-viewer 0.7.2 
print-atom 0.1.1 
print-code 0.7.1 
rst-preview 1.3.1 
sphinx-preview 0.1.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Arcanemagus** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/notifications/issues/174#issuecomment-331300920. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
