### ISSUE TITLE
Right-clicking window with no tabs produces this error

### ISSUE THREAD

**Issue by karai17** [atom/notifications#38]
```
Uncaught SyntaxError: Unexpected end of input
```

```
file:///C:/Users/Karai/AppData/Local/atom/app-0.179.0/resources/app/static/index.html?loadSettings=%7B%22pathToOpen%22%3Anull%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CKarai%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.179.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CKarai%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.179.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.179.0%22%2C%22shellLoadTime%22%3A357%2C%22initialPath%22%3Anull%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at BufferedProcess.exit (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\node_modules\notifications\lib\user-utilities.js:125:31)
  at BufferedProcess.triggerExitCallback (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Karai\AppData\Local\atom\app-0.179.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)
```

**Comment by benogle** [comment]
This can be closed then?

**Comment by karai17** [comment]
Yes.
