### ISSUE TITLE
All issues are blamed on atom-beautify

### ISSUE THREAD

**Issue by raphinesse** [atom/notifications#49]
The title says it all. Every error notification I receive blames `atom-beautify`, even when I can confirm the errors occur elsewhere.

Of all installed 3rd party packages `atom-beautify` is the smallest package regarding alphabetical order for what it's worth.

**Comment by benogle** [comment]
Can you click the clipboard icon on some of those errors, and paste in the contents? Where are the errors occurring if not in atom-beautify?

**Comment by raphinesse** [comment]
1. Generate sample package
2. Add `throw new Error("I'm an arbitrary Error")` as `my-package.coffe`'s first line
3. Reload window and run command `my-package:toggle`

**Atom Version**: 0.187.0
**System**: ZEUS
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.22.3

### Stack Trace

Failed to activate the my-package package

```
At I'm an arbitrary Error

Error: I'm an arbitrary Error
  at Object.<anonymous> (C:\Users\raphinesse\github\my-package\lib\my-package.coffee:1:11)
  at Object.<anonymous> (C:\Users\raphinesse\github\my-package\lib\my-package.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:672:34)
  at Package.module.exports.Package.activateConfig (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:257:12)
  at Package.module.exports.Package.activateNow (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:236:14)
  at C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:742:29
  at Emitter.module.exports.Emitter.emit (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:227:20)
  at C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:21.8 my-package:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsonlint",
      "linter-htmlhint",
      "turbo-javascript",
      "emmet",
      "atom-keymap-compatible-master"
    ],
    "autoHideMenuBar": true
  },
  "atom-beautify": {
    "_analyticsUserId": "fb6b96d0-cc6d-4ffc-b99d-0eb5d0afdc7f"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.15.0
coffee-compile, v0.11.0
editor-stats, v0.17.0
editorconfig, v0.3.2
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
keyboard-localization, v1.1.5
language-diff, v0.3.0
language-lua, v0.9.0
language-nunjucks, v1.3.0
linter, v0.12.0
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
my-package, v0.0.0
permute, v0.1.0
revert-buffer, v0.5.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Weird. Do you have atom-beautify enabled?

**Comment by raphinesse** [comment]
Yes

**Comment by raphinesse** [comment]
In case it means anything: the above package list is not complete. I have other packages installed that were not included by atom

**Comment by benogle** [comment]
Do you have `atom-beautify` cloned locally?

**Comment by raphinesse** [comment]
I'm pretty sure that I installed it using the GUI package manager.
Am 19.03.2015 02:25 schrieb "Ben Ogle" <notifications@github.com>:

**Comment by thomasjo** [comment]
Can you please, temporarily, move or rename your `~/.atom` folder, and then check if you're able to reproduce [your earlier result](https://github.com/atom/notifications/issues/49#issuecomment-83034479)? 

I'm pretty confident something is fairly broken with the state of your configuration and/or package installations.

**Comment by raphinesse** [comment]
I wouldn't have thought it myself, but it's indeed still reproducible after a profile wipe:

1. Move `~/.atom` folder
2. Install atom-beautify
3. Proceed like [before](#issuecomment-83034479)

**Atom Version**: 0.187.0
**System**: ZEUS
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.22.3

### Stack Trace

Failed to activate the my-package package

```
At I'm an arbitrary Error

Error: I'm an arbitrary Error
  at Object.<anonymous> (C:\Users\raphinesse\github\my-package\lib\my-package.coffee:1:11)
  at Object.<anonymous> (C:\Users\raphinesse\github\my-package\lib\my-package.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:672:34)
  at Package.module.exports.Package.activateConfig (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:257:12)
  at Package.module.exports.Package.activateNow (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:236:14)
  at C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:742:29
  at Emitter.module.exports.Emitter.emit (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:227:20)
  at C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\raphinesse\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:24.5 my-package:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
my-package, v0.0.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> 2 Install atom-beautify

How exactly did you install the package? It's interesting that it's not listed in the Installed Packages section. 

You noticed this in a previous comment as well -- you said that some packages were installed but weren't listed. Is there any difference in how you installed those packages which were not listed than then ones which were listed?

**Comment by raphinesse** [comment]
I installed it with the GUI package manager (the one in atom's settings)

**Comment by raphinesse** [comment]
Again using my old profile folder, I just now received a notofication which blamed another package than atom-beautify. Will investigate further when I have some time on my hands. *WTF is going on...* :confused::question:

**Comment by izuzak** [comment]
Thanks, @raphinesse. Did you use that to install all packages? Any idea why some packages are not shown in the list of installed packages?

Also, in case you _don't_ install atom-beautify but you do install some other package -- what happens if you try and trigger the error again?

**Comment by izuzak** [comment]
Cool, let us know if you find anything. Very strange :stuck_out_tongue_winking_eye: problem.

**Comment by raphinesse** [comment]
Will do so. Very strange indeed...

**Comment by raphinesse** [comment]
I can't reproduce the described behavior anymore. Even though I still use my old profile. Thanks for your patience and sorry for the inconvenience.
