### ISSUE TITLE
Failed to activate the go-plus package

### ISSUE THREAD

**Issue by sleeper** [atom/notifications#50]
[Enter steps to reproduce below:]

Update of the package from an older version

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.1
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.35.0

### Stack Trace

Failed to activate the go-plus package

```
At undefined is not a function

TypeError: undefined is not a function
  at addSplitLinesToContainer (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:256:20)
  at atom-notification.NotificationElement.render (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:84:11)
  at atom-notification.NotificationElement.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:38:33)
  at Object.createView (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:88:42)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:72:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:59:21)
  at Object.Notifications.addNotificationView (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:122:58)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/main.js:29:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at NotificationManager.module.exports.NotificationManager.addNotification (/Applications/Atom.app/Contents/Resources/app/src/notification-manager.js:54:20)
  at NotificationManager.module.exports.NotificationManager.addFatalError (/Applications/Atom.app/Contents/Resources/app/src/notification-manager.js:45:19)
  at Package.module.exports.Package.handleError (/Applications/Atom.app/Contents/Resources/app/src/package.js:905:33)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:247:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Users/fred/.atom/packages/settings-view/lib/package-manager.coffee:160:25
  at exit (/Users/fred/.atom/packages/settings-view/lib/package-manager.coffee:29:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:31.5 window:install-shell-commands (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "useReactEditor": true,
    "disabledPackages": [
      "highlight-line"
    ]
  }
}
```

### Installed Packages

```coffee
# User
dash, v1.1.0
emmet, v2.3.6
git-log, v0.3.0
language-dockerfile, v0.1.0
language-scala, v1.1.0
seti-syntax, v0.3.3
seti-ui, v0.6.3
settings-view, v0.187.0
status-bar, v0.66.0
tree-view-breadcrumb, v0.4.1
update-package-dependencies, v0.9.0
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @sleeper.

@benogle Looks like this failed [here](https://github.com/atom/notifications/blob/99eb09787dbb8a1c9668473cd5cab6ae6e75705b/lib/notification-element.coffee#L199):

```coffee
addSplitLinesToContainer = (container, content) ->
  for line in content.split('\n')
    ...
```

It seems that `split` didn't exist as a method of `content`, so the whole thing :boom:. Should we guard against such situations somehow? And if this really was caused because go-plus failed to activate, should the Notifications package have created an issue on that package instead of here? Needles to say, I'm a bit confused by this issue.

**Comment by izuzak** [comment]
This was reported again in https://github.com/atom/notifications/issues/78. Again, it seems that something goes wrong in the `addSplitLinesToContainer` method in the Notifications package while creating a notification, so the exception is reported here, instead of on the package. Definitely seems like there's a problem in this package as well, thought.

@benogle @kevinsawicki for :thought_balloon:

**Comment by kevinsawicki** [comment]
Yeah, looks like a non string detail property on the notification will blow it up and should be guarded against.
