### ISSUE TITLE
Copying test error throws Unhandled promise rejection with TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mnquintana** [atom/notifications#70]
This ~~may have~~ definitely has something to do with https://github.com/atom/notifications/pull/64:

Clicking on the copy button from a test error notification triggered with <kbd>Cmd-Alt-T</kbd> throws an Unhandled Promise rejection with the following error and stack trace:

```
TypeError: undefined is not a function
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/user-utilities.js:83:21
    at Object.module.exports.linuxVersionText (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/user-utilities.js:82:14)
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/user-utilities.js:39:36
    at Object.module.exports.getOSVersion (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/user-utilities.js:31:14)
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-issue.js:109:41
    at NotificationIssue.module.exports.NotificationIssue.getIssueBody (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-issue.js:103:14)
    at HTMLAnchorElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:180:30)
```

Also clicking on the "Create issue" button does nothing.

OS: Ubuntu 14.10
Atom 0.204.0

**Comment by despairblue** [comment]
Same thing here on arch linux with 0.205.0

**Comment by despairblue** [comment]
To anyone who's having trouble reporting bugs because of this:
```
apm install notifications@0.49.0
```

Installing the old version kind of fixes this. `Copy to Clipboard` works again. The `Create Issue` button doesn't work for the first exception, but for every one following the first one.
