### ISSUE TITLE
Failed to activate the php-debug package

### ISSUE THREAD

**Issue by minsoe** [atom/notifications#77]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.53.0

### Stack Trace

Failed to activate the php-debug package

```
At undefined is not a function

TypeError: undefined is not a function
  at addSplitLinesToContainer (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:315:20)
  at atom-notification.NotificationElement.render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:97:11)
  at atom-notification.NotificationElement.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:50:33)
  at Object.createView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:95:42)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:74:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:61:21)
  at Object.Notifications.addNotificationView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:129:58)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:33:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at NotificationManager.module.exports.NotificationManager.addNotification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:54:20)
  at NotificationManager.module.exports.NotificationManager.addFatalError (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:45:19)
  at Package.module.exports.Package.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:939:33)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:247:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.17.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
This seems to be an issue with the php-debug package. Can you open an issue on that repo?

**Comment by izuzak** [comment]
@benogle I think this is related to https://github.com/atom/notifications/issues/50#issuecomment-89629883, and might be a problem in the notifications package (in addition to a problem in the community package which triggers the original notification).
