### ISSUE TITLE
when open atom, notification will report error on the right above corner

### ISSUE THREAD

**Issue by angelia-yuqi** [atom/notifications#83]
Uncaught TypeError: undefined is not a function
C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:315

**Comment by izuzak** [comment]
Can you share the full stack trace and other details for the error? There should be a copy-to-clipboard icon at the bottom of the red notification.

Also, it seems that you're using Atom 0.208.0. Can you try updating to Atom 1.0.0 and see if that resolves the problem?

**Comment by angelia-yuqi** [comment]
TypeError: undefined is not a function
  at addSplitLinesToContainer (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:315:20)
  at atom-notification.NotificationElement.render (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:93:9)
  at atom-notification.NotificationElement.initialize (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:50:33)
  at Object.createView (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\main.js:95:42)
  at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\src\view-registry.js:74:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\src\view-registry.js:61:21)
  at Object.Notifications.addNotificationView (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\main.js:129:58)
  at C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\notifications\lib\main.js:33:24
  at Emitter.module.exports.Emitter.emit (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at NotificationManager.module.exports.NotificationManager.addNotification (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\src\notification-manager.js:54:20)
  at NotificationManager.module.exports.NotificationManager.addWarning (C:\Users\sesa380012\AppData\Local\atom\app-0.208.0\resources\app.asar\src\notification-manager.js:37:19)
  at ChildProcess.<anonymous> (C:\Users\sesa380012\.atom\packages\autocomplete-python\lib\provider.coffee:53:28)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:166:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1055:12)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

**Comment by izuzak** [comment]
See https://github.com/atom/notifications/issues/42#issuecomment-107975474, that problem should be fixed in a more recent version of Atom. Again, please update to Atom 1.0.

**Comment by angelia-yuqi** [comment]
I update to Atom 1.0.0, and the problem is be fixed. Thank you very much.
