### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by richardruiter** [atom/notifications#97]
[Enter steps to reproduce below:]
1. Have a split pane open on the right
2. Try to close tabs on the right pane

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.59.0
### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:631

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:631:15)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Notification.module.exports.Notification.dismiss (/usr/share/atom/resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```
### Commands

```
     -3:05.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:58.7.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -2:54.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:53.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:52.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:30.2.0 core:delete (atom-text-editor.editor.is-focused)
     -2:29.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:10.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.2.0 plantuml-viewer:toggle (atom-text-editor.editor.is-focused)
     -1:00.9.0 core:cut (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:47.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:46.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:46 core:save (atom-text-editor.editor.is-focused)
  6x -0:16.5.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "Termrk",
      "formatter",
      "remote-sync",
      "node-debugger"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.8
api-blueprint-preview, v0.6.0
atom-beautify, v0.28.14
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
autocomplete-erlang, v1.1.1
browser-plus, v0.0.42
language-api-blueprint, v1.0.2
language-erlang, v3.0.0
language-gherkin, v1.0.3
language-plantuml, v0.1.1
language-typescript-grammars-only, v1.3.0
linter, v1.6.0
markdown-preview-plus, v2.2.2
plantuml-viewer, v0.7.0
terminal-plus, v0.11.2

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
Can you reproduce this in atom's safe mode? (`atom --safe` from the cli or `Application: Open Safe` in the command panel)

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/notifications/issues/97#issuecomment-152164119. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
